### ISSUE TITLE
sticky-table-header mis aligns when the parent container is given some fixed width and not set to 100%.

### ISSUE THREAD

**Issue by sachitp** [bcherny/angular-sticky-table-header#39]
When the parent where the sticky-table-header is included, is given a fixed width, the header comes out of the parent as the sticky-header gets positioned to "position: fixed" when user starts scrolling.

When the width of the sticky-header[ Lets say 1800px ] is more than the width assigned to the parent[ 1600px ] ,the sticky-header spills out of the parent and breaks the UI.

It works absolutely fine when the width of the parent is not fixed to some numbers[100%], but when the parent is given some width, it tends to break.

**Comment by bcherny** [comment]
fixed in #40
